create table if not exists posts (
    post_id integer generated by default as identity,
    post_title varchar(50) not null,
    post_content varchar(2048) not null,
    post_image_url varchar(256) not null,
    constraint pk_post_id primary key (post_id)
);

create table if not exists comments (
    comment_id integer generated by default as identity,
    post_id integer not null,
    comment_content varchar(300) not null,
    constraint pk_comment_id primary key (comment_id),
    constraint fk_comment_post foreign key (post_id) references posts (post_id) on delete cascade
);

create index if not exists idx_comments_post_id on comments (post_id);

create table if not exists tags (
    tag_id integer generated by default as identity,
    tag_name varchar(16) not null,
    constraint pk_tag_id primary key (tag_id)
);

create table if not exists posttags (
    posttags_id integer generated by default as identity,
    post_id integer not null,
    tag_id integer not null,
    constraint pk_posttags_id primary key (posttags_id),
    constraint fk_posttags_post_id foreign key (post_id) references posts(post_id) on delete cascade,
    constraint fk_posttags_tag_id foreign key (tag_id) references tags(tag_id) on delete set null,
    constraint uq_post_tag unique (post_id, tag_id)
);

create index if not exists idx_posttagspost_id on posttags (post_id);

create table if not exists postlikes (
    postlikes_id integer generated by default as identity,
    post_id integer not null,
    constraint pk_postlikes_id primary key (postlikes_id),
    constraint fk_postlikes_post_id foreign key (post_id) references posts(post_id) on delete cascade
);

create index if not exists idx_postlikes_post_id on postlikes (post_id);

insert into tags(tag_name) values
    ('Компьютеры'),
    ('Путешествия'),
    ('Котики'),
    ('Красивое');

-- Данные для первичной проверка работы блога
insert into posts(post_title, post_content, post_image_url) values
    ('Пост 1', 'Это пост номер 1', '/img/img.png'),
    ('Пост 2', 'Это пост номер 2', '/img/img.png'),
    ('Пост 3', 'Это пост номер 3', '/img/img.png'),
('Пост 4', 'Это пост номер 4', '/img/img.png'),
('Пост 5', 'Это пост номер 5', '/img/img.png'),
('Пост 6', 'Это пост номер 6', '/img/img.png'),
('Пост 7', 'Это пост номер 7', '/img/img.png'),
('Пост 8', 'Это пост номер 8', '/img/img.png'),
('Пост 9', 'Это пост номер 9', '/img/img.png'),
('Пост 10', 'Это пост номер 10', '/img/img.png'),
('Пост 11', 'Это пост номер 11', '/img/img.png'),
('Пост 12', 'Это пост номер 12', '/img/img.png'),
('Пост 13', 'Это пост номер 13', '/img/img.png'),
('Пост 14', 'Это пост номер 14', '/img/img.png'),
('Пост 15', 'Это пост номер 15', '/img/img.png'),
('Пост 16', 'Это пост номер 16', '/img/img.png'),
('Пост 17', 'Это пост номер 17', '/img/img.png'),
('Пост 18', 'Это пост номер 18', '/img/img.png'),
('Пост 19', 'Это пост номер 19', '/img/img.png'),
('Пост 20', 'Это пост номер 20', '/img/img.png'),
('Пост 21', 'Это пост номер 21', '/img/img.png'),
('Пост 22', 'Это пост номер 22', '/img/img.png'),
('Пост 23', 'Это пост номер 23', '/img/img.png');

insert into posttags(post_id, tag_id) values
    (1, 3),
    (1, 4),
    (5, 3),
    (6, 3),
    (7, 3),
    (8, 3),
    (9, 3),
    (10, 3),
    (11, 3),
    (12, 3),
    (13, 3),
    (14, 3),
    (15, 3),
    (16, 3),
    (17, 3),
    (18, 3);
