create table if not exists posts (
    post_id integer generated by default as identity,
    post_title varchar(256) not null,
    post_content varchar(2048) not null,
    post_image_url varchar(256) not null,
    constraint pk_post_id primary key (post_id)
);

create table if not exists comments (
    comment_id integer generated by default as identity,
    post_id integer not null,
    comment_content varchar(300) not null,
    constraint pk_comment_id primary key (comment_id),
    constraint fk_comment_post foreign key (post_id) references posts (post_id) on delete cascade
);

create table if not exists tags (
    tag_id integer generated by default as identity,
    tag_name varchar(16) not null,
    constraint pk_tag_id primary key (tag_id)
);

create table if not exists posttags (
    posttags_id integer generated by default as identity,
    post_id integer not null,
    tag_id integer not null,
    constraint pk_posttags_id primary key (posttags_id),
    constraint fk_posttags_post_id foreign key (post_id) references posts(post_id) on delete cascade,
    constraint fk_posttags_tag_id foreign key (tag_id) references tags(tag_id) on delete set null,
    constraint uq_post_tag unique (post_id, tag_id)
);

insert into tags(tag_name) values
    ('Компьютеры'),
    ('Путешествия'),
    ('Котики'),
    ('Красивое');

-- Данные для первичной проверка работы блога
insert into posts(post_title, post_content, post_image_url) values
    ('Пост 1', 'Это пост номер 1', '/img/img.png'),
    ('Пост 2', 'Это пост номер 2', '/img/img.png'),
    ('Пост 3', 'Это пост номер 3', '/img/img.png');

insert into posttags(post_id, tag_id) values (1, 3), (1,4);
